alias vim="nvim"
alias explore="cosmic-files &"
alias cu="cd .."
alias mkcd='{ IFS= read -r d && mkdir "$d" -p && cd "$d"; } <<<'
alias q="exit"
alias ..="cd .."
alias cls="clear"
alias gs="git status"
alias gaa="git add -A"
alias files="cosmic-files & disown"
